### ISSUE TITLE
Add location to the schedule

### ISSUE THREAD

**Issue by Chris-Johnston** [UWB-ACM/uwb-hacks#11]
The schedule should be updated to include the location of where things are happening.

**Comment by bpas247** [comment]
Do we have a list of the locations of all of the events on the schedule?

**Comment by Chris-Johnston** [comment]
workshops are in the NCEC, everything else in the arc, basically. same as last year.

**Comment by Chris-Johnston** [comment]
realized that all of the events on the list are actually in the NCEC
