### ISSUE TITLE
Schedule missing clearly defined breakfast

### ISSUE THREAD

**Issue by cforcomputer** [UWB-ACM/uwb-hacks#13]
> How much does this cost?
> Admission is completely free, including breakfast, lunch, dinner, and snacks.

There is a clearly defined time for lunch and dinner, but no defined time for breakfast beyond "morning coffee" 

Opinion: If there is not a proper breakfast, it should not be mentioned in the questions section to avoid confusing people regarding food.

**Comment by Chris-Johnston** [comment]
we could just replace "breakfast" with "morning coffee"

**Comment by cforcomputer** [comment]
Excellent

**Comment by Chris-Johnston** [comment]
technically not fixed yet
