### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by mduw** [UWB-ACM/uwb-hacks#48]
• teams
• price
• applicant requirements
• technical requirements
• tracks

**Comment by michelechao** [comment]
Animation glitch for "Are there any rules", including some text appearing below while still collapsed

**Comment by michelechao** [comment]
Remove "Keep discussions on-topic" duplicate

**Comment by michelechao** [comment]
Under "What if I don't have a team?" struggling is misspelled and recommended is misspelled

**Comment by michelechao** [comment]
"Will there be UWB Hacks from Home swag?" add a comma after "Unfortunately"

**Comment by michelechao** [comment]
"What are tracks" change Interaction to Interact

**Comment by michelechao** [comment]
"How will UWB Hacks from Home run remotely?" replace "event calendar" with "schedule"

**Comment by michelechao** [comment]
"Do I have to be a student?" "Yes, however, we accept all students from not only high schools, community colleges, and universities, but non-traditional institutions like boot camps and academies as well."

**Comment by michelechao** [comment]
Bold question on hover

**Comment by michelechao** [comment]
Center "+" and "-" for each question

**Comment by michelechao** [comment]
Match the font size for questions and answers
