### ISSUE TITLE
HOME PAGE

### ISSUE THREAD

**Issue by mduw** [UWB-ACM/uwb-hacks#51]
Landing block 
About
Tracks
Schedule
Guest speaker

**Comment by dannybanko** [comment]
Include Schedule when available

**Comment by dannybanko** [comment]
Fix the main section of the homepage

**Comment by dannybanko** [comment]
Change event dates to Cyan

**Comment by dannybanko** [comment]
Join Discord and Register Buttons should be visibly selected when tabbing through website
